/**
 * Searchable job / role titles (same list as SignUp "What do you do").
 * Used for contract "Project type" when user selects Other.
 */
export const FREELANCER_JOB_TITLES = [
    "Frontend Developer", "Backend Developer", "Fullstack Engineer", "Software Engineer",
    "Web Developer", "Mobile App Developer", "iOS Developer", "Android Developer",
    "Game Developer", "AR/VR Developer", "Embedded Systems Engineer",
    "API Developer", "SDK Developer", "Plugin Developer",
    "Shopify Developer", "WordPress Developer", "Webflow Developer",
    "Bubble Developer", "No-Code Developer", "Low-Code Developer",
    "Automation Engineer", "Zapier Expert", "Make (Integromat) Specialist",
    "UI/UX Designer", "Product Designer", "Graphic Designer", "Motion Designer",
    "Brand Designer", "Logo Designer", "Illustrator", "Animator",
    "Video Editor", "Short-form Video Editor", "YouTube Editor",
    "3D Artist", "VFX Artist", "Game Artist", "Storyboarding Artist",
    "Presentation Designer", "Pitch Deck Designer",
    "Content Writer", "Copywriter", "Technical Writer", "Ghostwriter",
    "Scriptwriter", "Blog Writer", "SEO Writer", "LinkedIn Ghostwriter",
    "Twitter Ghostwriter", "Email Copywriter", "Sales Copywriter",
    "Editor", "Proofreader", "Resume Writer",
    "Digital Marketer", "SEO Specialist", "Local SEO Specialist",
    "Technical SEO Expert", "SEM Specialist", "Google Ads Specialist",
    "Meta Ads Specialist", "TikTok Ads Specialist",
    "Social Media Manager", "Content Strategist",
    "Email Marketing Specialist", "Marketing Automation Specialist",
    "Performance Marketer", "Growth Hacker",
    "Conversion Rate Optimization Specialist",
    "Affiliate Marketer", "Influencer Marketer",
    "Brand Strategist", "Marketing Analyst",
    "Data Scientist", "Data Analyst", "Machine Learning Engineer",
    "AI Engineer", "AI Researcher", "Prompt Engineer",
    "LLM Engineer", "AI Automation Specialist",
    "Business Intelligence Analyst", "Data Engineer",
    "Data Visualization Specialist", "Analytics Engineer",
    "Blockchain Engineer", "Smart Contract Developer",
    "Solidity Developer", "Rust Blockchain Developer",
    "Web3 Engineer", "Smart Contract Auditor",
    "Crypto Analyst", "Tokenomics Specialist",
    "NFT Artist", "NFT Community Manager", "DAO Manager",
    "DevOps Engineer", "Cloud Architect", "Cloud Engineer",
    "AWS Specialist", "Azure Engineer", "GCP Engineer",
    "Site Reliability Engineer", "Platform Engineer",
    "Infrastructure Engineer", "System Administrator",
    "Kubernetes Specialist",
    "Cybersecurity Analyst", "Ethical Hacker",
    "Penetration Tester", "Bug Bounty Hunter",
    "Security Engineer", "Security Consultant",
    "SOC Analyst", "Digital Forensics Analyst",
    "Product Manager", "Associate Product Manager",
    "Technical Product Manager", "Project Manager",
    "Program Manager", "Scrum Master",
    "Agile Coach", "Operations Manager",
    "Business Analyst", "Financial Analyst",
    "Startup Consultant", "Management Consultant",
    "Accountant", "Bookkeeper", "Tax Consultant",
    "Virtual CFO", "Investment Analyst",
    "Equity Research Analyst",
    "Sales Executive", "Sales Closer",
    "Business Development Manager",
    "Cold Email Specialist", "Lead Generation Specialist",
    "Appointment Setter",
    "Customer Support Specialist",
    "Customer Success Manager",
    "Account Manager",
    "HR Manager", "Recruiter",
    "Technical Recruiter",
    "Talent Acquisition Specialist",
    "HR Consultant", "People Operations Specialist",
    "Online Tutor", "Course Creator",
    "Instructional Designer",
    "Corporate Trainer", "Language Tutor",
    "Coding Instructor",
    "Virtual Assistant", "Executive Assistant",
    "Data Entry Specialist", "Transcriptionist",
    "Research Assistant", "Email Manager",
    "Legal Consultant", "Contract Drafting Specialist",
    "Compliance Officer", "Privacy Consultant",
    "Content Creator", "YouTuber",
    "Podcaster", "Voice Over Artist",
    "Streamer", "UGC Creator",
    "Influencer", "Community Manager",
    "Discord Moderator",
    "Mechanical Engineer", "Civil Engineer",
    "Electrical Engineer", "CAD Designer",
    "Architectural Designer",
    "E-commerce Manager", "Shopify Store Manager",
    "Amazon FBA Specialist", "Etsy Seller Consultant",
    "Dropshipping Expert",
    "Product Listing Specialist",
    "Supply Chain Analyst",
    "Telemedicine Doctor", "Nutritionist",
    "Dietitian", "Fitness Coach",
    "Yoga Instructor", "Mental Health Counselor",
    "Life Coach",
    "Translator", "Interpreter",
    "Subtitling Specialist", "Localization Expert",
    "No-Code SaaS Builder", "Indie Hacker",
    "Micro-SaaS Developer",
    "Newsletter Operator",
    "Notion Consultant", "Airtable Specialist",
    "Community Growth Manager",
    "Online Reputation Manager",
    "Personal Branding Consultant",
    "Digital Product Seller",
];
